### ISSUE TITLE
Implementar e documentar extrapolação de dados

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#11]
**Descrição**

O frontend não envia todos os dados necessários para uma boa predição pois eles não estão presentes lá. Por isso, deve-se usar os dados do frontend para extrapolar outros dados (como latitude e longitude sendo usadas para descobrir clima). Isso deve acontecer entre uma request e sua resposta.

**Critérios de aceitação**

- [x] Explorar todo o conjunto possível de dados para cada um dos campos que serão extrapolados e **especificar um formato** tanto para o **time de modelagem** quanto para o **time de dataset**.
- [x] Documentar no drive, no arquivo "Arquitetura da API".
- [x] Extrapolar clima a partir de latitude e longitude no endpoint.
- [x] Extrapolar dia da semana, hora e data no endpoint.

**Comment by NilvanPeres** [comment]
O campo 'clima' que é retornado da API OpenWeather, será padronizado para cinco valores:  chuvoso, nublado, sol, neve e atmosphere. Os tipos que API retorna pode ser encotrado em https://openweathermap.org/weather-conditions#Weather-Condition-Codes-2 . O intuito é padronizar a resposta com o que é mostrado no dataset.

**Comment by NilvanPeres** [comment]
Os campos de dia/data/hora estão no formato PT-BR. Sendo data = dd/mm/YYYY. Horário = HH/mm/ss. E dias = [segunda-feira, terça-feira, quarta-feira, quinta-feira, sexta-feira, sábado, domingo]. O horário mostrado será de acordo com o fuso-horário da região.

**Comment by satsfy** [comment]
@juninhigh Onde eu posso encontrar o código?
