### ISSUE TITLE
Criar arquitetura da API

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#4]
Criar um documento de especificações para os seguintes parâmetros cujas requisições possuem, em ordem cronológica de etapa:

1. [x] Como serão recebidos os dados do usuário;
2. [x] Como serão extrapolados (clima, velocidade...);
3. [x] Como serão alimentados para rede neural;
4. [x] Como será processada a resposta da rede neural;
5. [x] Como será retornada a resposta para o usuário.

**Comment by satsfy** [comment]
Uma informação importante que acredito ser útil salientar é a seguinte: se quisermos a velocidade do usuário, teremos que guardar o IP dele e utilizá-lo para podermos conseguir sua mudança de posição (bem como o tempo entre essas posições) de forma a calcular sua velocidade.

Considerando isso tenho alguns fatores a levantar:

- Como mantemos os dados anônimos?
- Como guardamos e recuperamos esse dado de maneira fácil?
- Como garantimos que a velocidade calculada é uma estimativa razoável?
- Quais condições permitem esse cálculo e quais não?
- Como garantimos que o usuário vai ter predições mesmo que a conexão venha a cair?

**Comment by satsfy** [comment]
Levando em contas várias questões sobre os usuários, seria bom existir alguma forma de guardar os IP's dos usuários para podermos manter organizados os dados sobre eles.

**Comment by satsfy** [comment]
## Perguntas interessantes sobre questões de Machine Learning

#### Nós vamos prever o quê? 

Se formos prever apenas a chance de uma categoria de acidente em dada região, então temos alguns problemas:

1. Qual seria o real valor da nossa aplicação? Talvez seja overhead criar esse serviço.

2. Dado que múltiplas categorias de acidente estão em jogo a cada momento, refletiremos apenas o mais relevante ou vários riscos?

3. Se refletimos apenas o mais importante, então passaremos uma visão incompleta para o usuário sobre os riscos que está exposto fazendo o usuário baixar a guarda no trânsito e ironicamente aumentando o risco de acidente que ele sofre. 

4. Se refletiremos além do que é mais relevante, corremos o risco de passar informação demais e isso atrapalhar sua direção, ironicamente aumentando o risco de acidente que ele sofre. 

#### Se formos prever também a chance de um acidente em dada região

1. Levando em conta que nós possuímos um dataset de **acidentes**, nós não possuímos informações sobre todos os carros que passaram pelo mesmo local dos acidentes e **não se acidentaram**. É possível fazer essa predição sem esses dados? Seria possível extraír dados de fluxo veicular em certas regiões para fazer cálculos como "acidentes por quilômetro quadrado por fluxo veícular"?

2. Por isso, uma densidade maior de acidentes em dada região não faz dela mais perigosa: pode ser ela seja mais segura que outras regiões com densidade menor de acidentes, mas o seu número é maior, pois mais carros passam ali. Se for possível fazer essa previsão, como fazer ela sem vieses? 

3. Ainda nessa veia: o que é uma região, nesse contexto? Levando em conta que a geometria computacional vai fazer uma tarefa complicada definir o que é uma região, seria possível fazer um heatmap ou algo semelhantemente simples para definir o que é um local com muitos acidentes e o que é um local com poucos?

#### Como vamos lidar com dados envolvendo latitude e longitude?

1. Será se simplesmente alimentar esses dados para a rede neural já é o suficiente para conseguir resultados coerentes?

2. Vamos supor que não. Porque então? Se os dados forem incongruentes fora das pistas de tráfego veicular não tem problema, porque não é ali que foi feito para usar. O importante é serem congruentes **apenas** em pistas.

3. Caso não, como faríamos para preprocessar esses dados?

**Comment by jps12** [comment]
> Uma informação importante que acredito ser útil salientar é a seguinte: se quisermos a velocidade do usuário, teremos que guardar o IP dele e utilizá-lo para podermos conseguir sua mudança de posição (bem como o tempo entre essas posições) de forma a calcular sua velocidade.
> 
> Considerando isso tenho alguns fatores a levantar:
> 
> * Como mantemos os dados anônimos?
> * Como guardamos e recuperamos esse dado de maneira fácil?
> * Como garantimos que a velocidade calculada é uma estimativa razoável?
> * Quais condições permitem esse cálculo e quais não?
> * Como garantimos que o usuário vai ter predições mesmo que a conexão venha a cair?

Uma das soluções possiveis é guardando a ultima localização do usuário e pegando a atual e medindo a distância. Algumas tecnologias permitem isso importante salientar algumas coisas: 
* Se a o espaço de tempo for pequeno, a medida da velocidade vai ser melhor, em contrapartida, tem que se considerar o volome de processamento que irá aumentar consideravelmente fazendo consultas a APIs que retornam a distância.
* Se o espaço de tempo for maior então um outro problema é que o usuário pode: Andar em alta velocidade um boa parte do percuso, parar em um local (por qualquer motivo que seja) e continuar, pegando os dados entre essas localizações a velociade maxima não vai ser descoberta.

Com relação ao espaço de tempo das requisições da velocidade para cada escolha o problema pode tender a um desses dois topicos apresentados.

**Comment by GabrielOak** [comment]
> Uma informação importante que acredito ser útil salientar é a seguinte: se quisermos a velocidade do usuário, teremos que guardar o IP dele e utilizá-lo para podermos conseguir sua mudança de posição (bem como o tempo entre essas posições) de forma a calcular sua velocidade.
> 
> Considerando isso tenho alguns fatores a levantar:
> 
> * Como mantemos os dados anônimos?
> * Como guardamos e recuperamos esse dado de maneira fácil?
> * Como garantimos que a velocidade calculada é uma estimativa razoável?
> * Quais condições permitem esse cálculo e quais não?
> * Como garantimos que o usuário vai ter predições mesmo que a conexão venha a cair?

Uma alternativa muito boa para isso é utilizar websocket. Não vai ser necessário salvar o ip do usuário e toda vez que ele entrar no app, vai ser criado uma conexão com api e, através do websocket, ele vai poder passar e receber dados em tempo real. 
No Django existe o [Django Channels](https://channels.readthedocs.io/en/latest/) que faz essa comunicação por websocket.
