### ISSUE TITLE
Definir os outputs para a rede neural

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#5]
**Descrição**

Para a previsão de acidentes que podem acontecer, é necessário definir categorias de saídas para a rede neural. Essas categorias podem ser extraídas e extrapoladas a partir dos datasets existentes.

**Critérios de aceitação**

- [x] Uma lista de categorias de acidentes que sejam conseguentes com os datasets disponíveis. Deve ser documentada no Drive e nessa issue.

**Comment by satsfy** [comment]
A rede neural vai consistir dos seguintes outputs, um vetor unidimensional com as seguintes saídas:

| Categoria de saída | Exemplos | Mensagem da API (inglês) |
| - | - | - |
| Animais + Motorista | Animais na pista | Animals on the road | 
| Pedestre + Motorista | Atropelamento, Travessia de pedestres | People on the road |
| Entre motoristas | Colisão (traseira, frontal, transversal, ...), Engavetamento | Dangerous driving area |
| Pista perigosa + Motorista | Capotamento, Tombamento, Pista escorregadia | Dangerous road |
| Motoristas inatentos + Motorista | Falta de atenção, Dormindo, Avarias veiculares | Inattentive drivers | 
| Motoristas ousados + Motorista | Excesso de velocidade, Ingestão de álcool, Ultrapassagem | Dangerous drivers |
| Ambiente + Motorista | Pista escorregadia (chuva/neve), Visão limitada (nevoeiro) | Dangerous climate conditions |

**Comment by Gabrielle-Ribeiro** [comment]
@RenatoBrittoAraujo Com vetor unidimensional, você quer dizer um vetor que traga a probabilidade para cada uma dessas categorias de acidente? 
E algumas categorias não fazem muito sentido para mim, por exemplo, como a gente pode dizer que em tal lugar tem motoristas com falta de atenção ou até dormindo? Eu entendo que isso cause acidentes mas não sei se com Machine Learning a gente pode fazer esse tipo de afirmação. Essas categorias ainda estão meio obscuras pra mim.

**Comment by satsfy** [comment]
@Gabrielle-Ribeiro Eu digo no treinamento do dataset. Existem, nos datasets, saídas como "acidente causado por usuário dormindo no tráfego", "acidente causado por desatenção do motorista" e outras coisas assim. Nesse sentido, como existem datasets com categorias diferentes uns dos outros, seria interessante classificar essas instâncias de acidentes dentro de grandes categorias gerais como "motoristas inatentos" ou "motoristas dirigindo perigosamente".

Quanto aos valores de saída, você colocou uma boa incógnita sobre a questão: como vamos definir essas chances de acidente em dado local? Vamos conversando sobre isso.

**Comment by jps12** [comment]
@RenatoBrittoAraujo e @Gabrielle-Ribeiro Estava estudando uma solução que cria um mapa de calor usando a api do maps. Entretanto não sei como pegar a 'cor' de determinado tipo de acidente no mapa
[link]( https://developers.google.com/maps/documentation/javascript/examples/layer-heatmap?hl=pt-br)

**Comment by satsfy** [comment]
@jps12 Acho que a gente poderia fazer um BFS simples com quadrados de 100 metros de comprimento para gerar um heatmap (algoritmo simples). Mas fiz algumas considerações recentes e isso apresenta um problema sobre dados: 

Nós temos dados sobre acidentes apenas. Se fizermos um heatmap ingênuo como esse, podemos refletir de forma errônea os dados, porque não necessariamente uma área com muitos acidentes é uma área perigosa. Se mais carros passam ali todo dia, mas a média de acidentes é menor, estaríamos classificando essa área como perigosa quando não e tento assim, e o contra-caso é ainda mais perigoso: classificaríamos como seguras área com potencial alto de acidentes, que tem fluxo baixo de carros.

**Comment by jps12** [comment]
@RenatoBrittoAraujo considerando que o brasil tem aproximadamente mais de 4.500 km tanto em dimensões máximas norte-sul, quanto em leste-oeste, dividindo o brasil em quadrados de 100 metros teriamos 45.000x45.000 quadrados (a não ser que tenha um meio de desconsiderar os quadrados que se encontram fora do Brasil). O meu questionamento é: Dado que objetiva-se implementar para todo o mundo, é plausível essa abordagem?
Além disso temos memória e processamento suficiente disponível para tal nível de processamento de dados?

**Comment by satsfy** [comment]
Eu disse 100m mas pode ser qualquer valor na verdade. Vamos supor que seja 1km: o raio da terra é 6371km, comprimento transversal seria ~20000km. Logo seriam 4 elevado a oitava quadrados. Cada quadrado um inteiro contendo o número de acidentes proximos, logo 32 bits. Portanto ~380 megabytes de dados, o que é perfeitamente razoável. Para preencher e consultar consiste de carregar na memória (se feito assim que o servidor for levantado, gasta menos de um segundo), sendo uma operação tão pequena quanto O(1) consulta e preencher seria O(v^2), V seria o número de expansões no BFS, se V = 3 (valor razoável) temos que não gasta mais de 20 ciclos para preencher, quase O(1). A cada X segundos/minutos de treinamento, o heatmap é salvo na memória por redundância e assim, os dados ficam intactos e úteis.

Isso seria uma implementação simples que cumpre os objetivos @jps12, logo possivel é, mas ainda enviesado.
