### ISSUE TITLE
Busca e adaptação de datasets

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#6]
**Descrição**

É necessário ter dados de acidentes de trânsito para podermos fazer previsões. O objetivo dessa issue é acumular dados de forma a criar uma dataset nosso, de forma que possuam os mesmo input e outputs entre si.

Caso estejam faltando certos dados em algum dataset usado para compor esse, essa tabela faltante pode ser resolvida com duas soluções:

- Preferêncialmente, usar os dados que existem para extrapolar o dado faltante (exemplo: data + hora + local pode ser usado para encontrar o clima?)
- Caso não, deixa valor nulo (0? 0.5? ""? Fica a seu critério).

Depende da issue #5 para os categorias de saídas (vetor Y do dataset)

**Critérios de aceitação**

- [x] Dataset criado com colunas padronizadas e preenchidas (mesmo que seja com um valor nulo).
- [x] Dataset se encontra aqui no GitHub.
- [x] Existem documentações no Drive sobre o dataset (entradas, saídas, número de instâncias...).
- [x] Prover dataset simplificador para o time de modelagem (colocar no drive)

**Comment by jps12** [comment]
estou tendo problemas com a criação da padronização. Achei a api de geocoding mas ela retorna coodernada muitas vezes falhas e em outras vezes somente retorna nulo. 
Solução encontrada: Pesquisar o endereço, caso não consiga, pesquisa as coordenadas da cidade, ou da avenida.

**Comment by jps12** [comment]
O dataset do DF ja está padronizado, mas está enviesado, pois as coordenadas praticamente não deferem dentro de uma cidade, pois o logradouro dado pelo dataset não retorna uma coordenada usando a api do Geopy

**Comment by jps12** [comment]
Padronizei e deixei disponivel no drive os datasets em que temos as coordenadas geográficas. Falta apenas padronizar a causa do acidente. com relação a disponibilizar no git, Será necessário separar para não carregar um arquivo muito grande .

**Comment by GabrielOak** [comment]
Melhorias necessárias do dataset para aprimoramento do modelo:
1 - Fazer uma EDA (Exploratory data analysis).
2 - Fazer balanceamento dos dados.

**Comment by jps12** [comment]
@GabrielOak o dataset pode ser balanceado no preprocessamento do dataset: [link](https://sigmoidal.ai/como-lidar-com-dados-desbalanceados/)
