### ISSUE TITLE
Buscar e projetar modelo inicial

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#7]
**Descrição**

Buscar e/ou projetar um modelo que consiga classificar múltiplas categorias a partir de dados de uma tabela, voltado à prevenção de acidentes de trânsito. Envolve a criação de um documento para expor esse conhecimento ao time.

Isso requer também a criação de um código (simples) que seja já capaz de realizar tal previsão (por mais que esteja errada).

**Critérios de aceitação**

- [ ] Documento no Drive sobre modelos possíveis, bem como seus pontos fortes e fracos, além de fontes se houverem.
- [ ] Modelo simples, código aqui no GitHub (não precisa estar conectado com a API desde que existam instruções de como usar).

**Comment by satsfy** [comment]
Pergunta que seria legal se responder: qual seria a grande vantagem do nosso modelo se comparado a um K nearest neighbors?

**Comment by GabrielOak** [comment]
Pontos importantes para a melhoria do modelo inicial:
1 - Adicionar mais features a rede neural. 
2 - Encontrar uma maneira melhor de pré-processar os dados.
3 - Testar redes/modelos alternativos ao nosso.
