### ISSUE TITLE
Conexão com API de clima para determinada longitude e latitude

### ISSUE THREAD

**Issue by satsfy** [Carisk/Carisk-backend#8]
**Descrição**

Encontrar uma API meteorológica e criar um sistema simples que se conecte com essa API de clima, passe uma latitude e longitude e pegue o resultado retornado.

**Critérios de aceitação**

- [x] Deve printar os dados no terminal de clima para uma determinada latitude e longitude.

**Comment by NilvanPeres** [comment]
A api escolhida é do site https://openweathermap.org/api, por ser um site que tem várias API's sobre o clima. A utilizada será a Current Weather Data.
